# Generated by Django 2.2.2 on 2019-06-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20190622_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('link', models.URLField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='contactdetails',
            options={'verbose_name': 'Contact Details', 'verbose_name_plural': 'Contact Details'},
        ),
    ]
