# Generated by Django 2.2.2 on 2019-06-22 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_schedule'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schedule',
            new_name='ScheduleItem',
        ),
    ]
