# Generated by Django 2.2.2 on 2019-06-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_auto_20190622_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleitem',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
