# Generated by Django 2.2.2 on 2019-06-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_auto_20190622_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleitem',
            name='day',
            field=models.CharField(choices=[('Monday', 'Mon'), ('Tuesday', 'Tue'), ('Wednesday', 'Wed'), ('Thursday', 'Thu'), ('Friday', 'Fri'), ('Saturday', 'Sat'), ('Sunday', 'Sun')], max_length=50, unique=True),
        ),
    ]
