# Generated by Django 2.2.2 on 2019-06-20 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='photo',
            field=models.ImageField(null=True, upload_to='chefs/'),
        ),
    ]
