# Generated by Django 2.2.2 on 2019-06-20 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_chef_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chef',
            name='bio',
        ),
    ]
