# Generated by Django 2.2.2 on 2019-06-20 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_auto_20190619_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='photo',
            field=models.ImageField(null=True, upload_to='testimonials/'),
        ),
    ]
