# Generated by Django 2.2.2 on 2019-06-19 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_dish_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='css_active',
            field=models.BooleanField(default=False),
        ),
    ]
