# Generated by Django 2.2.2 on 2019-06-19 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_category_css_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='description',
            new_name='ingridients',
        ),
    ]
