# Generated by Django 2.2.2 on 2019-06-19 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_dish_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='speciality',
            field=models.BooleanField(default=False),
        ),
    ]
