# Generated by Django 2.2.2 on 2019-06-22 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='num_of_persons',
            new_name='number_of_persons',
        ),
    ]
