# Generated by Django 2.2.2 on 2019-06-22 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20190622_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='number_of_persons',
            new_name='persons',
        ),
    ]
