# Generated by Django 2.2.2 on 2019-06-23 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_auto_20190622_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='persons',
            field=models.PositiveIntegerField(),
        ),
    ]
