# Generated by Django 2.2.2 on 2019-06-23 00:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_auto_20190622_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='persons',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
